# Generated by Django 3.0.6 on 2020-05-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='frog_love',
            new_name='frog_lover',
        ),
    ]
