# Generated by Django 3.0.6 on 2020-05-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200515_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.TextField()),
            ],
        ),
    ]
