# Generated by Django 3.0.6 on 2020-05-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_randomfacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RandomFacts',
            new_name='Facts',
        ),
    ]
