# Generated by Django 3.0.6 on 2020-05-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200518_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facts',
            new_name='Fact',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='facts',
            new_name='fact',
        ),
    ]
